name: N3rdyBans
version: 1.0
description: Plugin de banimentos
main: com.n3rdydev.main
author: n3rdydev
database: true
commands:
  banir:
    description: bane um jogador.
    permission-message: §cSem permissao.
    usage: /ban player motivo
  unban:
    description: desbanir um jogador.
    permission-message: §cSem permissao.
    usage: /unban player